version: '3'

networks:
  dev:

services:
  nginx:
    container_name: nginx
    image: nginx:stable-alpine
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - './nginx.conf:/etc/nginx/nginx.conf'
      - /etc/letsencrypt/live/sechenov-inquierer.ru/fullchain.pem:/etc/letsencrypt/live/sechenov-inquierer.ru/fullchain.pem
      - /etc/letsencrypt/live/sechenov-inquierer.ru/privkey.pem:/etc/letsencrypt/live/sechenov-inquierer.ru/privkey.pem

    depends_on:
      - go_app
      - frontend
    networks:
      - dev

  go_app:
    container_name: go_app
    build:
      context: ./Sechenovka
    command: ./service  # Явно запускаем основной сервис
    volumes:
      - ./public:/app/public
      - ./db/storage:/app/data
    environment:
      - DATABASE_PATH=/app/data/master.db
    ports:
      - "3010:8080"
    networks:
      - dev
    restart: always

  push_sender:
    container_name: push_sender
    build:
      context: ./Sechenovka
    command: ./push_sender  # Явно запускаем push-сервис
    ports:
      - "3011:8081"
    networks:
      - dev
    restart: always


  frontend:
    container_name: frontend
    build:
      context: ./ui
    networks:
      - dev
    env_file:
      - ui/.env


volumes:
  node_modules:
