version: '3'
services:
  postgres:
    image: postgres:latest
    container_name: postgres
    ports:
      - '6500:5432'
    volumes:
      - progresDB:/data/postgres
    env_file:
      - ./app.env

  pgAdmin:
    image: dpage/pgadmin4
    container_name: pgAdmin
    env_file:
      - ./app.env
    ports:
      - "5050:80"

#  backend:
#    image: golang:1.20-alpine
#    container_name: backend
#    env_file:
#      - ./app.env
#    ports:
#      - "8000:8000"
#    depends_on:
#      - postgres
#      - pgAdmin

volumes:
  progresDB:
