version: '3.8'

services:
  app:
    build: .
    container_name: go_app
    volumes:
      - ./data:/app/data
      - ./public:/app/public
    environment:
      - DATABASE_PATH=/app/data/storage.db
    ports:
      - "8080:8080"