version: '3.8'

services:
  app:
    build: .
    container_name: go_app
    volumes:
      - ./data:/app/data
    environment:
      - DATABASE_PATH=/app/data/storage.db
    ports:
      - "8080:8080"
    depends_on:
      - db

  db:
    image: nouchka/sqlite3
    container_name: sqlite_db
    volumes:
      - ./data:/data
    command: /bin/sh -c "sleep infinity"
